# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsdine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
